DECLARE KMS_RESOURCE_NAME STRING;
DECLARE FIRST_LEVEL_KEYSET BYTES;

SET KMS_RESOURCE_NAME = """";
SET FIRST_LEVEL_KEYSET = FROM_BASE64('');

SELECT
  x,
  DETERMINISTIC_DECRYPT_STRING(
    KEYS.KEYSET_CHAIN(
      KMS_RESOURCE_NAME,
      FIRST_LEVEL_KEYSET
    ),
    encryptY,
    "additional-data"
  ) AS decryptY
FROM `project.dataset.table`;