DECLARE KMS_RESOURCE_NAME STRING;
DECLARE FIRST_LEVEL_KEYSET BYTES;

SET KMS_RESOURCE_NAME = "gcp-kms://projects/vpc-1-439422/locations/us/keyRings/us-test/cryptoKeys/us-test-key";
SET FIRST_LEVEL_KEYSET = FROM_BASE64('CiQA5pZLVz5JMUA0Eia/J1rRQ33VcyCpxKsf7GhPXYtyELEPwkQStwEAIbMsLE0QH80XrBUTxyUlsZKBExMFR0lKZYcoVC8DaWF0YjeakDQeydBOQr4V0mbakny4/be5pqWMDRyk2TB06VtD1ykZOJYP1p6C0mkB7e7mljvPeZMr9xbCKBL3qyJmd1EvX1g05d/qHj08Z8JC50oMxfxuFYrNpsnYRAjOP8cUuDjoR1QX1ogVjj95weC58XZpCd8HijFPGlS8FgPX/A2YvMz9IYge3ZGn8BcLqjXResT8cK4=');

SELECT
  x,
  DETERMINISTIC_DECRYPT_STRING(
    KEYS.KEYSET_CHAIN(
      KMS_RESOURCE_NAME,
      FIRST_LEVEL_KEYSET
    ),
    encryptY,
    "additional-data"
  ) AS decryptY
FROM `vpc-1-439422.kmsTest.Test2`;