DECLARE KMS_RESOURCE_NAME STRING;
DECLARE FIRST_LEVEL_KEYSET BYTES;

SET KMS_RESOURCE_NAME = """";
SET FIRST_LEVEL_KEYSET = FROM_BASE64('');

CREATE OR REPLACE TABLE `project.dataset.table` AS 
SELECT
  x,
  DETERMINISTIC_ENCRYPT(
    KEYS.KEYSET_CHAIN(
      KMS_RESOURCE_NAME,
      FIRST_LEVEL_KEYSET
    ),
    y,
    "additional-data"
  ) AS ff
FROM 
  `project.dataset.table`;
